# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designfeatures',
            name='lead_free',
            field=models.BooleanField(default=True),
        ),
    ]
