# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacon', '0002_auto_20170402_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designfeatures',
            name='thickness',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
